version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - GOPATH=/go
      - GOROOT=/usr/local/go
      - PATH=/usr/local/go/bin:/go/bin:${PATH}
    working_dir: /workspaces/envvars-cli

  # Add any additional services you might need here
  # For example, a database for testing:
  # postgres:
  #   image: postgres:15
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: envvars_cli_test
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres-data:

